name: Add competitor to list when confirmed by tag

on:
  issues:
    types: [labeled]
jobs:
    
  add-competitor:
    if: ${{ contains(github.event.issue.labels.*.name, 'registration') && contains(github.event.issue.labels.*.name, 'accepted') }}

    runs-on: ubuntu-latest
    steps:
      - name: Dump github.event
        run: echo '${{ toJson(github.event) }}'
        
      - name: Checkout files
        uses: actions/checkout@v2
        
      - name: Add competitor to file
        run: |
          body_text=$'${{ github.event.issue.body }}'
          echo $body_text
          regex='github.com/([[[:alnum:]._-]+/[[:alnum:]._-]+)'
          if [[ $body_text =~ $regex ]]
          then
              user_repo="${BASH_REMATCH[1]}"
              echo "${user_repo}"
              echo "${{ github.event.issue.number }}:$user_repo" >> competitors.txt
          else
              exit 1
          fi

      - name: Commit files
        run: |
            git config user.email "bot@example.com"
            git config user.name "Iam Acomputer"
            git add competitors.txt
            git commit -m "Here comes a new challenger!"
      - run: git push

      - uses: peter-evans/close-issue@v1
        with:
          comment: Here comes a new challenger! You have been added to the benchmark leaderboard.
