# This is a basic workflow to help you get started with Actions

name: Auto repo invite acceptation

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.REPO_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: list repo invites and keep the relevant one
        run: |
          invite_id=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /user/repository_invitations | jq '.[] | select(.repository.full_name=="TotallyRandomGus/hidden-inverted-pendulum") | .id')
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /user/repository_invitations/$invite_id
