name: Verify a competitor's repo

on:
  issues:
    types: [labeled]
jobs:
    
  verify-competitor:
    if: ${{ contains(github.event.issue.labels.*.name, 'participation') }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.REPO_TOKEN }}
    steps:
      - name: Dump github.event
        run: echo '${{ toJson(github.event) }}'
        
      - name: Isolate repo link
        run: |
          body_text=$'${{ github.event.issue.body }}'
          echo $body_text
          user_repo=$(grep -oE '[[:alnum:]._-]+/[[:alnum:]._-]+' <<< $body_text)
          echo $user_repo
          echo "USER_REPO=$user_repo" >> $GITHUB_ENV
        
      - name: Is repo link actually a repo?
        id: repo_check
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/$USER_REPO
        continue-on-error: true
      - name: If repo ref is broken, feedback in registration issue
        if: ${{ steps.repo_check.outcome != 'success' }}
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            There was a problem when checking your repository link. There might be a typo, look for extra spaces or punctuation.
            
      - name: Is repo link a benchmark entry repo?
        id: link_check
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$USER_REPO/contents/webots.yml
        continue-on-error: true
      - name: If repo link broken, feedback on registration issue
        if: ${{ steps.link_check.outcome == 'failure' }}
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            There was a problem when checking your repository link. You haven't added the organizer as a collaborator.
        
      - name: Does repo have a correctly named controller?
        if: ${{ steps.link_check.outcome == 'success' }}
        id: controller_check
        run: |
          svn export "https://github.com/$USER_REPO/trunk/controllers/$DEFAULT_CONTROLLER" --force \
            --username 'example@example.com' --password ${{ secrets.REPO_TOKEN }} --quiet --non-interactive
          ls "$DEFAULT_CONTROLLER/$DEFAULT_CONTROLLER"* -U
        env:
          DEFAULT_CONTROLLER: edit_me
      - name: If no controller found, feedback on registration issue
        if: ${{ steps.controller_check.outcome == 'failure' }}
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            There doesn't seem to be a controller in your repository. Please name your main controller with the default name "edit_me"
