name: Verify a competitor's repo when registering from issue form

on:
  issues:
    types: [labeled]
jobs:
  verify-competitor:
    if: ${{ join(github.event.issue.labels.*.name) == 'registration' }}
    uses: ./.github/workflows/verification.yml
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}