name: Verify a competitor's repo

on:
  issues:
    types: [labeled]
jobs:
    
  verify-competitor:
    #if: ${{ contains(github.event.issue.labels.*.name, 'participation') }}

    runs-on: ubuntu-latest
    steps:
      - name: Dump github.event
        run: echo '${{ toJson(github.event) }}'
        
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Isolate repo link
        run: |
          body_text=$'${{ github.event.issue.body }}'
          echo $body_text
          user_repo=$(grep -oE '[[:alnum:]._-]+/[[:alnum:]._-]+' <<< $body_text)
          echo $user_repo
          echo "USER_REPO=$user_repo" >> $GITHUB_ENV
        
      - name: Is repo link a benchmark entry repo?
        id: link_check
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$USER_REPO/contents/webots.yml
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: does repo have a correctly named controller?
        run: |
          svn export 'https://github.com/$USER_REPO/trunk/controllers/$DEFAULT_CONTROLLER' --force \
            --username 'example@example.com' --password $GITHUB_TOKEN --quiet --non-interactive
          ls "$DEFAULT_CONTROLLER/$DEFAULT_CONTROLLER"* -U
        env:
          DEFAULT_CONTROLLER: edit_me
      - name: If controller works
        run: echo 'the repo seems to be working'
