name: Individual competitor evaluation of their controller

run-name: "Individual evaluation of competitor ${{ github.event.issue.number }} : ${{ github.event.issue.user.login }}"

on: 
  issue_comment:
    types: [created]

jobs:
  record:
    if: >
      contains(github.event.issue.labels.*.name, 'registration') &&
      contains(github.event.issue.labels.*.name, 'accepted') &&
      github.event.issue.user.login == github.event.comment.user.login &&
      contains(github.event.comment.body, 'run')
    runs-on: ubuntu-latest
    steps:
      - name: Feedback on individual evaluation
        id: feedback
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Individual re-evaluation in progress...

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Isolate repo link
        run: |
          echo "INDIVIDUAL_REF=$(grep ./competitors.txt -e '^${{ github.event.issue.number }}:.*')" >> $GITHUB_ENV
          echo $INDIVIDUAL_REF

      - name: Record and update Benchmark animations
        uses: cyberbotics/benchmark-record-action@forkSystem 
        with:
          fetch_token: ${{ secrets.REPO_TOKEN }}
          individual_evaluation: "${{ env.INDIVIDUAL_REF }}"

      - name: Feedback on individual evaluation
        id: feedback
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ steps.feedback.outputs.comment-id }}
          body: Re-evaluation finished! The leaderboard is up to date.

      - name: Delete request comment
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
