# This is a basic workflow to help you get started with Actions

name: Individual competitor evaluation of their controller

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      repo_link:
        description: id:username/repoName
        default: 7:TotallyRandomGus/my-super-pendulum-controller

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Record and update Benchmark animations
        uses: cyberbotics/benchmark-record-action@forkSystem 
        with:
          fetch_token: ${{ secrets.REPO_TOKEN }}
          #individual_evaluation: ${{ inputs.repo_link }}
          
