name: Individual competitor evaluation of their controller

run-name: "Individual evaluation of competitor ${{ github.event.issue.number }} : ${{ github.event.issue.user.login }}"

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      repo_link:
        description: id:username/repoName
        default: 7:TotallyRandomGus/my-super-pendulum-controller
  
  issue_comment:
    types: [created]

jobs:
  record:
    if: >
      contains(github.event.issue.labels.*.name, 'registration') &&
      contains(github.event.issue.labels.*.name, 'accepted') &&
      github.event.issue.user.login == github.event.comment.user.login &&
      contains(github.event.comment.body, 'run')
    runs-on: ubuntu-latest
    steps:
      - name: Dump github.event
        run: echo '${{ toJson(github.event) }}'

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Isolate repo link
        run: bash .github/repo_regex.sh "${{ github.event.issue.body }}" "${{ github.event.issue.user.login }}"

      - name: Record and update Benchmark animations
        uses: cyberbotics/benchmark-record-action@forkSystem 
        with:
          fetch_token: ${{ secrets.REPO_TOKEN }}
          individual_evaluation: "${{ github.event.issue.number }}:${{ env.USER_REPO }}"
      
      - name: Delete request comment
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ env.USER_REPO }}/issues/comments/${{ github.event.comment.id }}
        env:
          GH_TOKEN: ${{ github.token }}
