name: Record and update Benchmark animations
run-name: "General evaluation of all competitors"

on:
  workflow_dispatch:
# Uncomment to run every midnight
#  schedule:
#    - cron:  '0 0 * * *'
jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Record and update Benchmark animations
        uses: cyberbotics/benchmark-record-action@forkSystem 
        with:
          fetch_token: ${{ secrets.REPO_TOKEN }}
