name: Remove user from list when asked

on:
  issues:
    types: [edited]
env: 
  GH_TOKEN: ${{ github.token }}
jobs:
  reset-entry:
    if: >
      contains(github.event.issue.labels.*.name, 'registration') &&
      contains(github.event.issue.labels.*.name, 'accepted')
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Remove user from competitors.txt
        run: sed -i '/^${{ github.event.issue.number }}:.*/d' competitors.txt

      - name: Push changes
        run: |
          git config --global user.name '${{ github.repository_owner }}'
          git config --global user.email '${{ github.repository_owner }}@users.noreply.github.com'
          git commit -am "Removed competitor from list"
          git push

      - name: Remove all labels

      - name: Message feedback
      